name: CI/CD Pipeline

on:
  push:
    branches: 
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_USER: root
          MYSQL_DATABASE: ressources_relationnelles_db        
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Prisma CLI
        run: npm install @prisma/cli

      - name: Install dependencies
        run: npm install

      - name: Run Prisma migrate (if needed)
        run: npx prisma migrate dev --preview-feature

      - name: Run Prisma generate
        run: npx prisma generate

      - name: Run unit tests
        run: npm test

      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://localhost:3000'

      - name: Deploy to Azure VM
        if: success() && github.ref == 'refs/heads/develop'
        env:
          AZURE_VM_IP: ${{ secrets.AZURE_SERVER }}
          AZURE_VM_USER: ${{ secrets.AZURE_USERNAME }}
          AZURE_VM_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        run: |
          sshpass -p $AZURE_VM_PASSWORD ssh -o StrictHostKeyChecking=no $AZURE_VM_USER@$AZURE_VM_IP "cd /path/to/your/app && docker-compose up -d"
